### PR TITLE
add zh_CN

### PR DESCRIPTION
**Pull request by Roddy1219**
Add language translation for zh_CN

### CODE REVIEW

**Comment by mderasse** [comment]
Hi,

Thank you,
I can see that the translation is not totally done,
Are you still working on it ?

**Comment by Roddy1219** [comment]
yes

**Comment by mderasse** [comment]
Ok, I will wait the final translation for merge that PR.

Thank you

**Comment by Roddy1219** [comment]
Successful

**Comment by mderasse** [comment]
Thank you, i will review it in a few hours and come back to you

**Comment by Roddy1219** [comment]
ok

**Comment by mderasse** [comment]
Thank you !

**Pull request merged**
